# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=70)),
                ('passw', models.CharField(max_length=120)),
                ('car_reg', models.CharField(max_length=80)),
                ('phone', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Person_Meta',
            fields=[
                ('customer_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('staff', models.BooleanField()),
            ],
        ),
    ]
